apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
secrets:
  - name: cd-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "nodes/metrics", "endpoints"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework